services: mongodb

language: ruby

cache: bundler

rvm:
  - '2.0.0-p648'
  - '2.1.8'
  - '2.2.4'
  - '2.3.0'
  - 'jruby-1.7.20'
  - 'jruby-9.0.4.0'
  - 'rbx-2.2.7'

gemfile:
  - gemfiles/rails_4.0.13.gemfile
  - gemfiles/activerecord_4.0.13.gemfile
  - gemfiles/rails_4.1.14.gemfile
  - gemfiles/activerecord_4.1.14.gemfile
  - gemfiles/rails_4.2.5.gemfile
  - gemfiles/activerecord_4.2.5.gemfile
  - gemfiles/rails_5.0.0.beta1.gemfile
  - gemfiles/activerecord_5.0.0.beta1.gemfile
  - gemfiles/mongoid_4.0.2.gemfile
  - gemfiles/mongoid_5.0.2.gemfile

matrix:
  fast_finish: true

script: 'bundle exec rake spec'
